from LinkedList import DoublyLinkedList

l = DoublyLinkedList()
l.initial_insert(2)
print(l.str())
l.insert_values([3,2,2])
print(l.str())
l.insert_values([3,2,2])
print(l.str())
l.delete(3)
print(l.str())
l.remove_at(1)
print(l.str())
l.insert_at_beginning(3)
print(l.str())
l.delete(3)
print(l.str())
l.delete(2)
print(l.str())
l.insert_values([4,4])
print(l.str())
l.clear()
print(l.str())
