from LinkedList import LinkedList

l = LinkedList[int]()
l.initial_insert(2)
print(l)
l.insert_values([3,2,2])
print(l)
l.remove_at(1)
print(l)
l.insert_at_beginning(3)
print(l)
l.delete(3)
print(l)
l.delete(2)
print(l)
l.insert_values([4,4])
print(l)
l.clear()
print(l)